export HOST_DB=''
export USER_DB=
export PWD_DB=
export DATABASE=
export SECRET_KEY=
export LIMIT_FILE_SIZE=
export ACCESS_KEY_ID=
export SECRET_ACCESS_KEY=
export REGION=
export BUCKET=
export BUCKET_ACL=
yarn test
